### ISSUE TITLE
mw-thesaurus--quit is throwing error

### ISSUE THREAD

**Issue by vinotes** [agzam/mw-thesaurus.el#4] opened 2018-11-24 05:28 UTC
mw-thesaurus--quit: Invalid function: (buffer (get-buffer mw-thesaurus-buffer-name))

**Comment by agzam** [comment] 2018-11-28 23:47
Hmm... I'll check that out.. Thanks

**Comment by agzam** [comment] 2019-06-20 22:57
I haven't seen anyone else reporting this, and have not able to reproduce it myself. Closing this for now.

**Closed as completed by agzam** 2019-06-20 22:57 UTC
